FROM oracle/graalvm-ce:19.2.0
COPY build/libs/todo-service-*-all.jar todo-service.jar

EXPOSE 8080
EXPOSE 8085
ENV JAVA_OPTS "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.rmi.port=8085 -Dcom.sun.management.jmxremote.port=8085 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
CMD java -Xmn32m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.rmi.server.hostname=$JMX_HOST -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar todo-service.jar
