FROM oracle/graalvm-ce:19.3.2 as graalvm
COPY . /home/app/todo-service
WORKDIR /home/app/todo-service
RUN yum install -y perf

RUN gu install native-image

RUN native-image --verbose --enable-all-security-services --no-server -cp 'build/libs/*'

CMD "perf record -F 99 -ag -- ./todo-service"
